// Generated by scripts/prepare.ts
import type {
  BundledThemeInfo,
  DynamicImportThemeRegistration,
} from 'shiki/core';

export const bundledThemesInfo: BundledThemeInfo[] = [
  {
    id: 'github-dark',
    displayName: 'GitHub Dark',
    type: 'dark',
    import: (() =>
      import(
        'shiki/themes/github-dark.mjs'
      )) as unknown as DynamicImportThemeRegistration,
  },
  {
    id: 'github-light',
    displayName: 'GitHub Light',
    type: 'light',
    import: (() =>
      import(
        'shiki/themes/github-light.mjs'
      )) as unknown as DynamicImportThemeRegistration,
  },
];

export type BundledTheme = 'github-dark' | 'github-light';

export const bundledThemes = Object.fromEntries(
  bundledThemesInfo.map((i) => [i.id, i.import])
) as Record<BundledTheme, DynamicImportThemeRegistration>;
