#!/usr/bin/env bash
# make sure the shellbang is set to bash and not sh. freaking WSL causing issues thinking the script is being ran in Windows
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npx lerna run --concurrency 1 pre-commit
